// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKJbaZlZ4Edz42BVBS93rebklf9zRubU',
    appId: '1:600083975808:web:86f5068a57b5c7cd3ca065',
    messagingSenderId: '600083975808',
    projectId: 'contacts-app-4e6f1',
    authDomain: 'contacts-app-4e6f1.firebaseapp.com',
    databaseURL: 'https://contacts-app-4e6f1-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-4e6f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYlBPJIBSh_gzGs4orL54viyjoTt5S7Y',
    appId: '1:600083975808:android:e94c352fef2521dc3ca065',
    messagingSenderId: '600083975808',
    projectId: 'contacts-app-4e6f1',
    databaseURL: 'https://contacts-app-4e6f1-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-4e6f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53Fw2n2MlyTBAz54guzeiBP96DnIsfl8',
    appId: '1:600083975808:ios:b881eb6e7165708e3ca065',
    messagingSenderId: '600083975808',
    projectId: 'contacts-app-4e6f1',
    databaseURL: 'https://contacts-app-4e6f1-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-4e6f1.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53Fw2n2MlyTBAz54guzeiBP96DnIsfl8',
    appId: '1:600083975808:ios:62847cc0541aefc03ca065',
    messagingSenderId: '600083975808',
    projectId: 'contacts-app-4e6f1',
    databaseURL: 'https://contacts-app-4e6f1-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-4e6f1.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
